# Generated by Django 5.0.4 on 2024-04-11 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_remove_place_lat_remove_place_lon_place_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='place',
            name='longitude',
        ),
        migrations.AddField(
            model_name='place',
            name='lat',
            field=models.FloatField(default=1, verbose_name='широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='lon',
            field=models.FloatField(default=1, verbose_name='долгота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='место'),
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(db_index=True, verbose_name='позиция'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=models.TextField(verbose_name='Описание длинное'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(max_length=512, verbose_name='Описание короткое'),
        ),
    ]
