# Generated by Django 5.0.4 on 2024-04-11 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_remove_place_latitude_remove_place_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='place',
            name='lon',
        ),
        migrations.AddField(
            model_name='place',
            name='latitude',
            field=models.FloatField(blank=True, default=1, verbose_name='Широта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='longitude',
            field=models.FloatField(blank=True, default=1, verbose_name='Долгота'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='places.place', verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(db_index=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=models.TextField(verbose_name='Длинное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='description_short',
            field=models.CharField(max_length=512, verbose_name='Короткое описание'),
        ),
    ]
