# Generated by Django 4.0 on 2024-04-12 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_img_alter_place_description_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='Позиция'),
        ),
    ]
